CREATE TABLE IF NOT EXISTS cp_tenants (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cp_projects (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_cp_projects_tenant (tenant_id)
);

CREATE TABLE IF NOT EXISTS cp_api_keys (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  project_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  key_hash VARCHAR(128) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  allowed_models_json JSON NOT NULL,
  revoked_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_cp_api_keys_hash (key_hash),
  KEY idx_cp_api_keys_scope (tenant_id, project_id)
);

CREATE TABLE IF NOT EXISTS cp_models (
  public_model VARCHAR(128) PRIMARY KEY,
  protocol VARCHAR(64) NOT NULL,
  capability VARCHAR(64) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cp_channels (
  id VARCHAR(64) PRIMARY KEY,
  provider_type VARCHAR(64) NOT NULL,
  base_url VARCHAR(1024) NOT NULL,
  credential_ref VARCHAR(128) NOT NULL DEFAULT '',
  encrypted_api_key TEXT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  timeout_millis BIGINT NOT NULL DEFAULT 30000,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cp_channel_models (
  channel_id VARCHAR(64) NOT NULL,
  public_model VARCHAR(128) NOT NULL,
  upstream_model VARCHAR(128) NOT NULL,
  PRIMARY KEY (channel_id, public_model),
  KEY idx_cp_channel_models_model (public_model)
);

CREATE TABLE IF NOT EXISTS cp_route_policies (
  id VARCHAR(128) PRIMARY KEY,
  public_model VARCHAR(128) NOT NULL,
  strategy VARCHAR(64) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_cp_route_model (public_model)
);

CREATE TABLE IF NOT EXISTS cp_route_candidates (
  route_id VARCHAR(128) NOT NULL,
  channel_id VARCHAR(64) NOT NULL,
  priority INT NOT NULL DEFAULT 1,
  weight INT NOT NULL DEFAULT 100,
  PRIMARY KEY (route_id, channel_id)
);

CREATE TABLE IF NOT EXISTS cp_price_rules (
  public_model VARCHAR(128) PRIMARY KEY,
  currency VARCHAR(16) NOT NULL,
  input_micros_per_token BIGINT NOT NULL DEFAULT 0,
  output_micros_per_token BIGINT NOT NULL DEFAULT 0,
  estimated_output_tokens BIGINT NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cp_limit_rules (
  public_model VARCHAR(128) PRIMARY KEY,
  qps BIGINT NOT NULL DEFAULT 0,
  tpm BIGINT NOT NULL DEFAULT 0,
  concurrency BIGINT NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cp_runtime_snapshots (
  version VARCHAR(128) PRIMARY KEY,
  checksum VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  payload_json JSON NOT NULL,
  error TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  active_at TIMESTAMP NULL,
  KEY idx_cp_runtime_snapshots_status (status, active_at)
);
