CREATE TABLE IF NOT EXISTS tasks (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  project_id VARCHAR(64) NOT NULL,
  api_key_id VARCHAR(64) NOT NULL,
  request_id VARCHAR(128) NOT NULL,
  idempotency_key VARCHAR(255) NOT NULL DEFAULT '',
  request_hash VARCHAR(128) NOT NULL,
  kind VARCHAR(64) NOT NULL,
  media_type VARCHAR(32) NOT NULL,
  model VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  progress INT NOT NULL DEFAULT 0,
  provider_type VARCHAR(64) NOT NULL DEFAULT '',
  channel_id VARCHAR(64) NOT NULL DEFAULT '',
  provider_task_id VARCHAR(128) NOT NULL DEFAULT '',
  input_json JSON NOT NULL,
  result_json JSON NULL,
  usage_json JSON NULL,
  error_code VARCHAR(128) NOT NULL DEFAULT '',
  error_message VARCHAR(512) NOT NULL DEFAULT '',
  callback_url VARCHAR(1024) NOT NULL DEFAULT '',
  metadata_json JSON NULL,
  balance_hold_id VARCHAR(64) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL,
  UNIQUE KEY uk_tasks_request (request_id),
  KEY idx_tasks_scope_status (tenant_id, project_id, status),
  KEY idx_tasks_provider_poll (status, provider_task_id, updated_at),
  KEY idx_tasks_provider_external (provider_type, provider_task_id)
);

CREATE TABLE IF NOT EXISTS task_idempotency_records (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  api_key_id VARCHAR(64) NOT NULL,
  endpoint VARCHAR(128) NOT NULL,
  idempotency_key VARCHAR(255) NOT NULL,
  request_hash VARCHAR(128) NOT NULL,
  resource_type VARCHAR(32) NOT NULL,
  resource_id VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_task_idempotency_scope (tenant_id, api_key_id, endpoint, idempotency_key),
  KEY idx_task_idempotency_resource (resource_type, resource_id),
  KEY idx_task_idempotency_expires (expires_at)
);

CREATE TABLE IF NOT EXISTS file_assets (
  id VARCHAR(64) PRIMARY KEY,
  tenant_id VARCHAR(64) NOT NULL,
  project_id VARCHAR(64) NOT NULL,
  api_key_id VARCHAR(64) NOT NULL,
  request_id VARCHAR(128) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  size_bytes BIGINT NOT NULL DEFAULT 0,
  mime_type VARCHAR(128) NOT NULL DEFAULT '',
  upload_path VARCHAR(512) NOT NULL DEFAULT '',
  file_url VARCHAR(1024) NOT NULL,
  download_url VARCHAR(1024) NOT NULL,
  source VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NULL,
  KEY idx_file_assets_scope (tenant_id, project_id, created_at)
);

CREATE TABLE IF NOT EXISTS callback_outbox (
  id VARCHAR(64) PRIMARY KEY,
  task_id VARCHAR(64) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  project_id VARCHAR(64) NOT NULL,
  url VARCHAR(1024) NOT NULL,
  payload_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL,
  retry_count INT NOT NULL DEFAULT 0,
  next_retry_at TIMESTAMP NOT NULL,
  last_error TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_callback_outbox_due (status, next_retry_at),
  KEY idx_callback_outbox_task (task_id)
);
